name: '🐞 Bug Report'
description: Report a Bug to Storybook Rsbuild
title: '[Bug]: '
labels: ['🐞 bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Before submitting, please note:

         - Confirm that your problem cannot be solved by official documentation.
         - Make sure you searched in the [Issues](https://github.com/rspack-contrib/storybook-rsbuild/issues) and didn't find the same issue.
         - If it's not bug report, please use the "💡 Feature Request" issue template instead.

  - type: textarea
    id: versions
    attributes:
      label: Version
      description: Run `npx envinfo --system --browsers --npmPackages 'storybook*rsbuild*'` in your project, and paste the output into the textarea below.
      placeholder: |
        System:
        Browsers:
        npmPackages:
      render: sh
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe the Bug, including screenshots, etc.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Reproduce link
      description: 'Please provide a simplest reproduction of the problem (minimal demo without redundant dependencies). A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required). You can create it on CodeSandbox ([<kbd>⌘</kbd>Click here to create](https://codesandbox.io/dashboard/recent)), or provide the URL of the project:'
      placeholder: paste link here
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Reproduce Steps
      description: Please provide the simplest steps so that we can quickly reproduce the problem.
      placeholder: |
        for example:
        1. execute `pnpm dev`
        2. find the error message in the console
    validations:
      required: true
